### 媒资文件列表
POST {{gateway_host}}/media/files?pageNo=1&pageSize=1
Content-Type: application/json

{
  "filename": "",
  "fileType": "",
  "auditStatus": ""
}

###（通过网关）查询所有媒体资源
POST localhost:63010/media/files?pageNo=1&pageSize=10
Content-Type: application/json

{
  "filename": "",
  "fileType": "",
  "auditStatus": ""
}


### 上传文件
POST {{media_host}}/media/upload/coursepic
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="1.jpg"
Content-Type: application/octet-stream

< d:/develop/upload/1.jpg

### 上传文件
POST localhost:63050/media/upload/coursepic
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="1.jpg"
Content-Type: application/octet-stream

< d:/develop/upload/1.jpg

###上传视频
POST localhost:63050/mediafiles

### 上传一张图片(作为课程的封面)
POST localhost:63050/media/upload/coursefile
Content-Type: multipart/form-data;form-data; name="filedata"; filename="filename"

< d:/develop/upload/1.jpg

### 测试使用md5从数据库中获取文件信息
POST localhost:63010/media/upload/checkfile?fileMd5=1d0f0e6ed8a0c4a89bfd304b84599d9c


### 测试使用查询到数据库已经存在的视频文件信息，进入到minio桶中进行查询
POST localhost:63010/media/upload/checkchunk?fileMd5=1f229319d6fed3431d2f9d06193a433b&chunk=0

### 测试上传一个分块
POST localhost:63050/media/upload/uploadchunk
Content-Type: multipart/form-data;form-data; name="filedata"; filename="filename"

< D:\minio\upload\chunk\0